# Generated by Django 6.0.3 on 2026-04-14 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('departure_datetime', models.DateTimeField()),
                ('expected_return_datetime', models.DateTimeField()),
                ('destination', models.TextField(blank=True, null=True)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('room_details', models.TextField(blank=True, null=True)),
                ('faculty_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('faculty_remarks', models.TextField(blank=True, null=True)),
                ('faculty_processed_at', models.DateTimeField(blank=True, null=True)),
                ('warden_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('warden_remarks', models.TextField(blank=True, null=True)),
                ('warden_processed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('actual_return_time', models.DateTimeField(blank=True, null=True)),
                ('overall_status', models.CharField(choices=[('pending_parent', 'Pending Parent'), ('pending_faculty', 'Pending Faculty'), ('pending_warden', 'Pending Warden'), ('approved', 'Approved'), ('out', 'Out'), ('denied_by_parent', 'Denied By Parent'), ('denied_by_faculty', 'Denied By Faculty'), ('denied_by_warden', 'Denied By Warden'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_parent', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outing_requests', to='accounts.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_processed_outings', to=settings.AUTH_USER_MODEL)),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_verified_outings', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outing_requests', to=settings.AUTH_USER_MODEL)),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warden_processed_outings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'created_at'], name='outings_out_student_9db4c5_idx'), models.Index(fields=['overall_status', 'departure_datetime'], name='outings_out_overall_74fec2_idx'), models.Index(fields=['expected_return_datetime', 'actual_return_time'], name='outings_out_expecte_1cf0b5_idx')],
            },
        ),
    ]
