# Generated by Django 5.1.15 on 2026-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outingrequest',
            name='security_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
